# Generated by Django 5.0.2 on 2024-03-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_area",
                    models.CharField(
                        choices=[
                            ("AGRO", "Agriculture, Food, and Natural Resources"),
                            ("ARCH", "Architecture and Construction"),
                            ("ARTS", "Arts, Audio/Video Technology, and Communication"),
                            ("EDU", "Education and Training"),
                            ("GOV", "Government and Public Administration"),
                            ("HES", "Health Science"),
                            ("IT", "Information Technology"),
                            ("LPL", "Law, Public Safety, Corrections, and Security"),
                            ("MKT", "Marketing"),
                            ("STEM", "Science, Technology, Engineering, and Math"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=5,
                    ),
                ),
                ("work_experience", models.TextField(max_length=1000)),
                ("projects", models.TextField(max_length=1000)),
            ],
        ),
    ]
